- hosts: all
  remote_user: root
  tasks:
  - name: add repo 
    ansible.builtin.command: echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10/ /' |  tee /etc/apt/sources.list.d/shells:fish:release:3.list

  - name: add repo key
    shell: curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_10/Release.key | gpg --dearmor |  tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null

  - name: apt update and apt installfish
    apt:
      name: fish
      update_cache: yes


  - name: config fish as default shell
    shell: echo /usr/local/bin/fish |  tee -a /etc/shells
    shell: chsh -s /usr/local/bin/fish
...